Added SentryConfigSection::getInt() and SentryConfig::getIntValue() to be able to directly read an int from a config file. Also created MessageDispatcherCommand which dispatches the incoming messages to the correct hookpoint.

diff --git a/plugs/ircbase/Makefile b/plugs/ircbase/Makefile
--- a/plugs/ircbase/Makefile
+++ b/plugs/ircbase/Makefile
@@ -6,8 +6,10 @@ LIBNAME= libircbase.so.1.0.0
 CPP= g++
 CPPFLAGS= -g3 -I./include -I./plugs/ircbase/include/ -fPIC -g -c -Wall
 LFLAGS= -g3 -shared -Wl,-soname,$(SONAME) -o ./$(LIBNAME)
+LIBTHREAD= /usr/lib/libthread.so.1.0.0
+LIBTHREADURL= http://svn.coenbijlsma.nl/libthread/
 
-all: $(EXTERNALFILES) $(FILES) objects
+all: libthreadexists $(EXTERNALFILES) $(FILES) objects
 		@mv ./$(LIBNAME) $(PLUGSDIR)/
 
 $(EXTERNALFILES):
@@ -24,5 +26,14 @@ clean:
 
 distclean: clean
 		@if [ -f ./$(PLUGSDIR)/$(LIBNAME) ]; then rm ./$(PLUGSDIR)/$(LIBNAME); fi
+
+libthreadexists:
+		@if [ -f $(LIBTHREAD) ]; then \
+			echo "libthread exists, continuing..."; \
+		else \
+			echo "Cannot continue because libthread is missing."; \
+			echo "You can obtain it from " $(LIBTHREADURL); \
+			exit 1; \
+		fi
 
 .PHONY: all clean distclean $(EXTERNALFILES) $(FILES) objects
